In [1]:
import os

os.getcwd()

'/home/asutosh/Documents/projects/ml_projects/nexus-local/src/notebooks'

In [2]:
import sqlite3

DB_PATH = "../../data/sqlite/nexus.db"
def get_all_tables(db_path=DB_PATH):
    with sqlite3.connect(db_path) as conn:
        cursor = conn.cursor()
        cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
        return [row[0] for row in cursor.fetchall()]

def get_table_data(table_name, db_path=DB_PATH):
    import pandas as pd
    with sqlite3.connect(db_path) as conn:
        return pd.read_sql_query(f"SELECT * FROM {table_name}", conn)

In [3]:
get_all_tables()

['chats', 'messages', 'sqlite_sequence']

In [4]:
get_table_data('chats')

,id,title,created_at
0,7c265395-742f-46c8-aecd-d0ffbb773e69,Flet CLI Command,2026-02-01 21:58:00.003758
1,405d1a5f-db14-40ed-986a-cc47adc89509,Run Flet Application Command,2026-02-01 22:05:18.726549

In [5]:
get_table_data('messages')

,id,chat_id,role,content,created_at
0,56,7c265395-742f-46c8-aecd-d0ffbb773e69,user,"Look into my scripts folder data and tell me, ...",2026-02-01 21:58:00.023134
1,57,7c265395-742f-46c8-aecd-d0ffbb773e69,assistant,Since the `local_search_tool` did not find any...,2026-02-01 22:00:39.368589
2,58,405d1a5f-db14-40ed-986a-cc47adc89509,user,"look into my scripts folder and tell me, which...",2026-02-01 22:05:18.738229
3,59,405d1a5f-db14-40ed-986a-cc47adc89509,assistant,The command to run the Flet Application is:\n\...,2026-02-01 22:06:53.952126

In [6]:
import lancedb
import pandas as pd

LANCEDB_PATH = "../../data/lancedb"

def list_lancedb_tables(db_path: str):
    """List all tables in the specified LanceDB database."""
    db = lancedb.connect(db_path)
    print(f'db: {db}')
    return db.table_names()

def preview_lancedb_table(db_path: str, table_name: str):
    """Preview the specified table from LanceDB."""
    db = lancedb.connect(db_path)
    print(f'db: {db}')
    table = db.open_table(table_name)
    df = table.search().to_pandas()
    return df

In [28]:
tables = list_lancedb_tables(LANCEDB_PATH)
tables

db: LanceDBConnection(uri='/home/asutosh/Documents/projects/ml_projects/nexus-local/src/notebooks/../../data/lancedb')

/tmp/ipykernel_13248/2108785660.py:10: DeprecationWarning: table_names() is deprecated, use list_tables() instead
  return db.table_names()

['nexus_parent_child']

In [29]:
df = preview_lancedb_table(LANCEDB_PATH, tables[0])
print(f'df: {len(df)}')
df.head(10)

db: LanceDBConnection(uri='/home/asutosh/Documents/projects/ml_projects/nexus-local/src/notebooks/../../data/lancedb')
df: 2

,vector,id,text,metadata
0,"[-0.008340597, 0.03564531, -0.17049636, -0.055...",391f6716-3a6a-41eb-a17a-20b52cbf57a4,# Identity: Nexus Local\n\nName: Nexus Local\n...,{'doc_id': '605eea2f-343d-444d-8e68-45569926e3...
1,"[-0.03598645, 0.048911184, -0.14325875, -0.050...",ced6fd93-4db0-47dc-a2e6-788afb2a1785,Capabilities:\n- I can read and index local fi...,{'doc_id': '605eea2f-343d-444d-8e68-45569926e3...

In [23]:
df.iloc[0]['text']

'This is a test document for parent ingestion strategy.'