In [7]:
import os

os.getcwd()

'/home/asutosh/Documents/projects/ml_projects/nexus-local/src/notebooks'

In [19]:
import sqlite3

DB_PATH = "../../data/sqlite/nexus.db"
def get_all_tables(db_path=DB_PATH):
    with sqlite3.connect(db_path) as conn:
        cursor = conn.cursor()
        cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
        return [row[0] for row in cursor.fetchall()]

def get_table_data(table_name, db_path=DB_PATH):
    import pandas as pd
    with sqlite3.connect(db_path) as conn:
        return pd.read_sql_query(f"SELECT * FROM {table_name}", conn)

In [16]:
get_all_tables()

['chats', 'messages', 'sqlite_sequence']

In [23]:
get_table_data('chats')

Empty DataFrame
Columns: [id, title, created_at]
Index: []

In [21]:
get_table_data('messages')

Empty DataFrame
Columns: [id, chat_id, role, content, created_at]
Index: []

In [53]:
import lancedb
import pandas as pd

LANCEDB_PATH = "../../data/lancedb"

def list_lancedb_tables(db_path: str):
    """List all tables in the specified LanceDB database."""
    db = lancedb.connect(db_path)
    print(f'db: {db}')
    return db.table_names()

def preview_lancedb_table(db_path: str, table_name: str):
    """Preview the specified table from LanceDB."""
    db = lancedb.connect(db_path)
    print(f'db: {db}')
    table = db.open_table(table_name)
    df = table.search().to_pandas()
    return df

In [54]:
tables = list_lancedb_tables(LANCEDB_PATH)
tables

db: LanceDBConnection(uri='/home/asutosh/Documents/projects/ml_projects/nexus-local/src/notebooks/../../data/lancedb')

/tmp/ipykernel_10544/2108785660.py:10: DeprecationWarning: table_names() is deprecated, use list_tables() instead
  return db.table_names()

['documents', 'folder_home_asutosh_documents_scripts']

In [57]:
df = preview_lancedb_table(LANCEDB_PATH, tables[1])
print(f'df: {len(df)}')
df.head(10)

db: LanceDBConnection(uri='/home/asutosh/Documents/projects/ml_projects/nexus-local/src/notebooks/../../data/lancedb')
df: 30

,vector,text,source,id
0,"[0.071886, 0.026490282, -0.13054971, -0.013193...",#!/usr/bin/env bash\n\n{ # this ensures the en...,/home/asutosh/Documents/scripts/nvm_install.sh,nvm_install.sh_0_-6602728289413350833
1,"[0.032219965, 0.029916024, -0.14819193, -0.019...",#\n# Outputs the location to NVM depending on:...,/home/asutosh/Documents/scripts/nvm_install.sh,nvm_install.sh_1_-2588286132666324914
2,"[0.005550893, 0.0623138, -0.11308222, 0.012568...","NVM_SOURCE_URL=""https://raw.githubusercontent....",/home/asutosh/Documents/scripts/nvm_install.sh,nvm_install.sh_2_-610965695741569167
3,"[0.04599023, -0.02677219, -0.110119335, -0.056...",#\n# Node.js version to install\n#\nnvm_node_v...,/home/asutosh/Documents/scripts/nvm_install.sh,nvm_install.sh_3_-5852733485872995893
4,"[0.052064292, -0.013692957, -0.13760747, -0.02...",install_nvm_from_git() {\n local INSTALL_DIR\...,/home/asutosh/Documents/scripts/nvm_install.sh,nvm_install.sh_4_3887356865230983963
5,"[0.055863596, 0.015141221, -0.16061811, -0.001...","local fetch_error\n if [ -d ""$INSTALL_DIR/.gi...",/home/asutosh/Documents/scripts/nvm_install.sh,nvm_install.sh_5_3133610039051587137
6,"[0.039333787, 0.020571576, -0.13860737, 0.0005...","|| command git --git-dir=""${INSTALL_DIR}/.git""...",/home/asutosh/Documents/scripts/nvm_install.sh,nvm_install.sh_6_-8376086535068074865
7,"[0.022154529, -0.009345732, -0.13586815, 0.004...","nvm_echo >&2 ""Failed to checkout the given ver...",/home/asutosh/Documents/scripts/nvm_install.sh,nvm_install.sh_7_1065521287474008406
8,"[0.040761247, -0.0010905552, -0.13182873, -0.0...","nvm_echo ""=> Compressing and cleaning up git r...",/home/asutosh/Documents/scripts/nvm_install.sh,nvm_install.sh_8_3447260448973955604
9,"[0.055499524, -0.016462713, -0.14524591, -0.01...","if [ -z ""$NODE_VERSION_LOCAL"" ]; then\n ret...",/home/asutosh/Documents/scripts/nvm_install.sh,nvm_install.sh_9_1577915199912454159