In [7]:
import os

os.getcwd()

'/home/asutosh/Documents/projects/ml_projects/nexus-local/src/notebooks'

In [19]:
import sqlite3

DB_PATH = "../../data/sqlite/nexus.db"
def get_all_tables(db_path=DB_PATH):
    with sqlite3.connect(db_path) as conn:
        cursor = conn.cursor()
        cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
        return [row[0] for row in cursor.fetchall()]

def get_table_data(table_name, db_path=DB_PATH):
    import pandas as pd
    with sqlite3.connect(db_path) as conn:
        return pd.read_sql_query(f"SELECT * FROM {table_name}", conn)

In [16]:
get_all_tables()

['chats', 'messages', 'sqlite_sequence']

In [23]:
get_table_data('chats')

Empty DataFrame
Columns: [id, title, created_at]
Index: []

In [21]:
get_table_data('messages')

Empty DataFrame
Columns: [id, chat_id, role, content, created_at]
Index: []