In [8]:
import os

os.getcwd()

'/home/asutosh/Documents/projects/ml_projects/nexus-local/src/notebooks'

In [9]:
import sqlite3

DB_PATH = "../../data/sqlite/nexus.db"
def get_all_tables(db_path=DB_PATH):
    with sqlite3.connect(db_path) as conn:
        cursor = conn.cursor()
        cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
        return [row[0] for row in cursor.fetchall()]

def get_table_data(table_name, db_path=DB_PATH):
    import pandas as pd
    with sqlite3.connect(db_path) as conn:
        return pd.read_sql_query(f"SELECT * FROM {table_name}", conn)

In [10]:
get_all_tables()

['chats', 'messages', 'sqlite_sequence']

In [11]:
get_table_data('chats')

,id,title,created_at
0,61566467-cdc0-4a5d-ae99-5f96e0b630ca,Local Game Ideas Storage,2026-02-07 17:36:03.212664
1,1658987c-1a16-4956-9423-adfe2d33849e,Game Concept Ideas,2026-02-07 18:25:13.568768
2,5e05d0d6-55b7-43f0-aead-91198cd214cf,Test Chat,2026-02-07 18:52:15.793738
3,d0bd847c-8331-4f39-b309-e8073bb8d053,Nested Learning Overview,2026-02-07 18:53:53.045384
4,c2cfdd0d-9a8d-4df8-abc2-bc2897188040,Travel Companion App\n\nTripMate is a mobile a...,2026-02-07 22:11:15.168767

In [6]:
get_table_data('messages')

Empty DataFrame
Columns: [id, chat_id, role, content, created_at]
Index: []

In [7]:
import lancedb
import pandas as pd

LANCEDB_PATH = "../../data/lancedb"

def list_lancedb_tables(db_path: str):
    """List all tables in the specified LanceDB database."""
    db = lancedb.connect(db_path)
    print(f'db: {db}')
    return db.table_names()

def preview_lancedb_table(db_path: str, table_name: str):
    """Preview the specified table from LanceDB."""
    db = lancedb.connect(db_path)
    print(f'db: {db}')
    table = db.open_table(table_name)
    df = table.search().to_pandas()
    return df

In [49]:
tables = list_lancedb_tables(LANCEDB_PATH)
tables

db: LanceDBConnection(uri='/home/asutosh/Documents/projects/ml_projects/nexus-local/src/notebooks/../../data/lancedb')

/tmp/ipykernel_6864/2108785660.py:10: DeprecationWarning: table_names() is deprecated, use list_tables() instead
  return db.table_names()

['folder_ingested_docs']

In [50]:
df = preview_lancedb_table(LANCEDB_PATH, tables[0])
print(f'df: {len(df)}')
df.head(25)

db: LanceDBConnection(uri='/home/asutosh/Documents/projects/ml_projects/nexus-local/src/notebooks/../../data/lancedb')
df: 434

,vector,id,text,metadata
0,"[-0.0016696511, 0.10262888, -0.16428384, -0.01...",4e89dc8c-6fc0-4248-aa24-16c34662956a,Nested Learning: The Illusion of Deep Learning...,"{'creationdate': '', 'creator': 'PyPDF', 'doc_..."
1,"[-0.035810124, 0.04729766, -0.12118276, -0.029...",c3855b96-4017-4333-8fc7-d93b6ac7ca41,taneously designing optimization algorithms to...,"{'creationdate': '', 'creator': 'PyPDF', 'doc_..."
2,"[0.028199255, 0.047389477, -0.15452419, -0.033...",c4ce0b5a-8b51-4b68-ac78-6770deb885b3,"cancontinually learn/memorize, self-improved, ...","{'creationdate': '', 'creator': 'PyPDF', 'doc_..."
3,"[0.0004587692, 0.06294541, -0.13560617, -0.072...",2836c686-23f7-4040-b4a8-bb90678788c0,"own context flow, and explain howin-context le...","{'creationdate': '', 'creator': 'PyPDF', 'doc_..."
4,"[0.0011115844, 0.09322051, -0.15690055, -0.053...",a1832c1b-d25f-45c6-b3f4-8e9ea808b451,"white-box nature, we advocate for its importan...","{'creationdate': '', 'creator': 'PyPDF', 'doc_..."
5,"[-0.036894232, 0.057515275, -0.15824823, -0.05...",14122343-fd12-4aaf-ba7a-84c81dd45032,"insight, we present a set of more expressive o...","{'creationdate': '', 'creator': 'PyPDF', 'doc_..."
6,"[0.0006475313, 0.037555013, -0.1623389, -0.083...",b5af647f-d9e1-4945-8e13-9c7efa8ebdfa,more powerful learning rules; (2) Self-Modifyi...,"{'creationdate': '', 'creator': 'PyPDF', 'doc_..."
7,"[-0.03161448, 0.021700233, -0.15445068, -0.079...",9e8c9928-9d80-4de1-a9fd-181608ed69eb,self-modifying sequence model with the continu...,"{'creationdate': '', 'creator': 'PyPDF', 'doc_..."
8,"[0.040654846, 0.061644178, -0.13100363, -0.060...",567d6508-070f-4beb-afdf-c3bfe5425ac0,"ready, and some materials, experiments, discus...","{'creationdate': '', 'creator': 'PyPDF', 'doc_..."
9,"[0.0070868907, 0.077577986, -0.19525492, -0.04...",10e8d9eb-b111-4b71-9af2-85fbe64bbbfd,Figure 1: The uniform and reusable structure a...,"{'creationdate': '', 'creator': 'PyPDF', 'doc_..."
10,"[0.00849341, 0.054699097, -0.14178246, -0.0162...",8fc96f6f-eaea-4c8c-b01f-2c9d8c139dc1,"For decades, AI research has focused on design...","{'creationdate': '', 'creator': 'PyPDF', 'doc_..."
11,"[0.010905591, 0.0681695, -0.15875217, -0.08969...",8046ddb6-9963-48b0-a85b-411b2d402961,"from natural data [9], deep representation lea...","{'creationdate': '', 'creator': 'PyPDF', 'doc_..."
12,"[0.0051673898, 0.0849865, -0.18201964, -0.0751...",c1089edd-cb42-44c2-8da0-9848d52862ed,"Stacking of multiple layers, as it is done in ...","{'creationdate': '', 'creator': 'PyPDF', 'doc_..."
13,"[-0.016734727, 0.10904882, -0.13971882, -0.066...",290cabef-f0c4-438c-b02d-e5c950cadcc2,a universal solution to all the challenges and...,"{'creationdate': '', 'creator': 'PyPDF', 'doc_..."
14,"[-0.0044826446, 0.09149671, -0.13663428, -0.01...",1efb6c17-685a-4658-bb96-fa2b8a41544e,"more layers [21, 22], leaving their ability to...","{'creationdate': '', 'creator': 'PyPDF', 'doc_..."
15,"[0.039789192, 0.0809788, -0.17595895, -0.04365...",ca4efcb7-3ebd-4fe7-9199-4779ca3d1b1c,hyperparameters; and (iv) The model’s ability ...,"{'creationdate': '', 'creator': 'PyPDF', 'doc_..."
16,"[-0.025830347, 0.05729715, -0.118832536, -0.05...",5bfb2944-e68b-4254-b37c-a1e2efd523c0,deep learning models concentrate on: (1) devel...,"{'creationdate': '', 'creator': 'PyPDF', 'doc_..."
17,"[-0.007834527, 0.090619326, -0.13268001, -0.08...",f0ec4773-1efb-4f66-b985-65d648d467f6,"when the “right” choice of architecture, objec...","{'creationdate': '', 'creator': 'PyPDF', 'doc_..."
18,"[-0.010813154, 0.047471497, -0.18695885, -0.05...",9e01a696-25c1-4c46-9e2c-3727233e1325,task-specific models to more general-purpose s...,"{'creationdate': '', 'creator': 'PyPDF', 'doc_..."
19,"[-0.036714133, -0.009793111, -0.16261506, -0.0...",09b17dcc-986b-4ee3-9d11-d4aa8f69d9b3,that they successfully perform tasks learned d...,"{'creationdate': '', 'creator': 'PyPDF', 'doc_..."
20,"[-0.012716925, 0.002120929, -0.16515428, -0.05...",90ccfa9e-99ed-4976-b24d-15c3272dd6d3,that they successfully perform tasks learned d...,"{'creationdate': '', 'creator': 'PyPDF', 'doc_..."
21,"[-0.003358536, 0.007919367, -0.14105843, -0.06...",9fac2217-d8b9-4014-b93f-3ffd02a823dc,recent efforts to overcome the static nature o...,"{'creationdate': '', 'creator': 'PyPDF', 'doc_..."
22,"[0.0022554337, 0.022437686, -0.16586185, -0.08...",de9497f8-0603-4234-b2d7-13a99a381e41,models and if a new learning paradigm beyond s...,"{'creationdate': '', 'creator': 'PyPDF', 'doc_..."
23,"[0.058903787, -0.013363577, -0.1567542, -0.105...",b2ff728a-89be-479f-a5f8-5b87c2d8383f,person cannot form new long-term memories afte...,"{'creationdate': '', 'creator': 'PyPDF', 'doc_..."
24,"[0.032148782, 0.05025852, -0.16980834, -0.0563...",5fb8d12b-5d34-49ce-bafa-ed67b9be9d13,suffer from a similar pattern. Their knowledge...,"{'creationdate': '', 'creator': 'PyPDF', 'doc_..."

In [53]:
for row in df.iterrows():
    if 'jigsaw' in row[1]['metadata']['source']:
        print(f">> {row[1]['metadata']['source']} => {row[1]['text']}")

In [27]:
!ls '../../../../../'

 dashcam_complain		       'Procedural Generation in Games'
'google sys design 2 interview sheet'   projects
 ingested_docs			        scripts
 installations			        temp
 models				        temp1
 moltbook-agent			        temp_docs
 nayash.github.io		        Twine
 nayash.github.io-copy		        VIDEO_25072025194247_1753452767879.mp4
 notes

In [28]:
for root, _, files in os.walk('../../../../../ingested_docs'):
    print(f'root={root}, _={_}, files={files}')

root=../../../../../ingested_docs, _=['Private & Shared'], files=['NestedLearning.pdf']
root=../../../../../ingested_docs/Private & Shared, _=['Project Ideas'], files=['Project Ideas 70e616392f9446499e6f7da93016ddcf_all.csv', 'Project Ideas 70e616392f9446499e6f7da93016ddcf.csv']
root=../../../../../ingested_docs/Private & Shared/Project Ideas, _=['Recommendation system', '@Side-Hustle Ideas', 'Writing ideas', 'Nexus Local', 'TripMate'], files=['Notion templates to sell 283f28196ab68006a5abea65343349c1.md', 'Nexus Local 2edf28196ab68069b5b3c793ee2d68cb.md', 'Chrome extension to save snippets 282f28196ab680f19319c5036dc02319.md', 'Android expense tracker 258f28196ab680c4946efcbfb3be4ded.md', 'Recommendation system 106f28196ab680e38b96dcc192f58323.md', 'Writing ideas eb82935e544e4f55a7721b855efdd7af.md', 'Text Based Adventure - Abaddon Hotel cae65a64c0e04f8a9c64898ed4bda2a2.md', 'Android Chat Agent 258f28196ab680168ea1ffcbc1bdd26c.md', 'TripMate efd9cb3c97f04ae8ab8e67e78cd0a814.md', 'Android App for 2D, 3D geometry drawing & calculat 288f28196ab68058a0ebf86c20345afa.md', 'Android auto completion keyboard 288f28196ab680849b69c5f8c71c1576.md', 'P2P on Android ef0d33164c9f4a47a03cebbfff55196c.md', '@Side-Hustle Ideas 288f28196ab68037a8c9f93235e39762.md', '[Game] simple, adictive, level-based game built us 2c6f28196ab6809c8b06f6e847143ef6.md', '[cancel] Extension to do google search on text sel 289f28196ab6804c8f4ddb91d6ff7d3f.md', '[App] smart launcher with full home support using  2c6f28196ab680369f7dd21b15201849.md', 'E-Book publishing 223f28196ab68023b6d9d7bb458f8ec2.md', '[Game] multiplayer game like Undercover 2c6f28196ab680cc8b15e2699720448f.md', 'Sell on Gumroad 262f28196ab68070860cc077cbe468fa.md', '[Game] Jigsaw puzzle 2d7f28196ab680608e2bc6d5bd54da59.md', '[App] show word meaning as popup pn context menu c 292f28196ab680bea984e0982c4e9ad1.md', 'Try anti gravity ide 2edf28196ab680ae94eeebc82a44b44b.md', '[Game] Neon Rebus (Emoji translation) 2d5f28196ab680b485ffe1a24a9ad49a.md', '[Game] MemShuffle тАФ Card shuffle memory 2d5f28196ab6806bbaf4e01779f2e719.md']
root=../../../../../ingested_docs/Private & Shared/Project Ideas/Recommendation system, _=[], files=['Screenshot_from_2025-08-16_19-09-20.png']
root=../../../../../ingested_docs/Private & Shared/Project Ideas/@Side-Hustle Ideas, _=[], files=['NotebookLM Edu Videos 2edf28196ab680fcbd44ef788863769e.md']
root=../../../../../ingested_docs/Private & Shared/Project Ideas/Writing ideas, _=[], files=['Writing tips 236f28196ab680f1be3df0c5a13372d1.md', 'E-Book Ideas 27af28196ab68093bbcbe32bd8de95bf.md', 'DINOv3 250f28196ab68138a4bede4b4afa2466.md']
root=../../../../../ingested_docs/Private & Shared/Project Ideas/Nexus Local, _=[], files=['Product Requirement Document (PRD) Nexus-Local 2f1f28196ab680488781d6e64a33ddbe.md']
root=../../../../../ingested_docs/Private & Shared/Project Ideas/TripMate, _=[], files=['Commands a502fc8b63044edfae5143caee97322a.md', 'ChatGPT response 132f28196ab680a180a2f532d8613628.md']