In [1]:
import os

os.getcwd()

'/home/asutosh/Documents/projects/ml_projects/nexus-local/src/notebooks'

In [2]:
import sqlite3

DB_PATH = "../../data/sqlite/nexus.db"
def get_all_tables(db_path=DB_PATH):
    with sqlite3.connect(db_path) as conn:
        cursor = conn.cursor()
        cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
        return [row[0] for row in cursor.fetchall()]

def get_table_data(table_name, db_path=DB_PATH):
    import pandas as pd
    with sqlite3.connect(db_path) as conn:
        return pd.read_sql_query(f"SELECT * FROM {table_name}", conn)

In [3]:
get_all_tables()

['chats', 'messages', 'sqlite_sequence']

In [4]:
get_table_data('chats')

,id,title,created_at
0,7c265395-742f-46c8-aecd-d0ffbb773e69,Flet CLI Command,2026-02-01 21:58:00.003758
1,405d1a5f-db14-40ed-986a-cc47adc89509,Run Flet Application Command,2026-02-01 22:05:18.726549

In [5]:
get_table_data('messages')

,id,chat_id,role,content,created_at
0,56,7c265395-742f-46c8-aecd-d0ffbb773e69,user,"Look into my scripts folder data and tell me, ...",2026-02-01 21:58:00.023134
1,57,7c265395-742f-46c8-aecd-d0ffbb773e69,assistant,Since the `local_search_tool` did not find any...,2026-02-01 22:00:39.368589
2,58,405d1a5f-db14-40ed-986a-cc47adc89509,user,"look into my scripts folder and tell me, which...",2026-02-01 22:05:18.738229
3,59,405d1a5f-db14-40ed-986a-cc47adc89509,assistant,The command to run the Flet Application is:\n\...,2026-02-01 22:06:53.952126

In [6]:
import lancedb
import pandas as pd

LANCEDB_PATH = "../../data/lancedb"

def list_lancedb_tables(db_path: str):
    """List all tables in the specified LanceDB database."""
    db = lancedb.connect(db_path)
    print(f'db: {db}')
    return db.table_names()

def preview_lancedb_table(db_path: str, table_name: str):
    """Preview the specified table from LanceDB."""
    db = lancedb.connect(db_path)
    print(f'db: {db}')
    table = db.open_table(table_name)
    df = table.search().to_pandas()
    return df

In [17]:
tables = list_lancedb_tables(LANCEDB_PATH)
tables

db: LanceDBConnection(uri='/home/asutosh/Documents/projects/ml_projects/nexus-local/src/notebooks/../../data/lancedb')

/tmp/ipykernel_13248/2108785660.py:10: DeprecationWarning: table_names() is deprecated, use list_tables() instead
  return db.table_names()

['nexus_parent_child']

In [18]:
df = preview_lancedb_table(LANCEDB_PATH, tables[0])
print(f'df: {len(df)}')
df.head(10)

db: LanceDBConnection(uri='/home/asutosh/Documents/projects/ml_projects/nexus-local/src/notebooks/../../data/lancedb')
df: 19

,vector,id,text,metadata
0,"[-0.01833202, 0.010185653, -0.18143885, -0.051...",7686aad8-7334-491a-8c06-3926fb69b00f,# ChatGPT response\n\n[ChatGPT](https://chatgp...,{'doc_id': 'ebde81f4-9975-433d-a618-b683e2a427...
1,"[0.005449516, -0.0043293536, -0.17812338, -0.0...",bdcf1ea7-40f1-4931-a577-8029a94b07fc,- **Framework**: Use **Node.js** (with **Expre...,{'doc_id': 'ebde81f4-9975-433d-a618-b683e2a427...
2,"[0.017679704, 0.07456504, -0.18708915, -0.0274...",396164f5-bc98-4151-96cd-45ba59234489,- **Database**: Use a database like **PostgreS...,{'doc_id': 'ebde81f4-9975-433d-a618-b683e2a427...
3,"[0.04005739, 0.033952005, -0.16843913, -0.0641...",b59b0f94-ced2-43cd-9ffa-8ef831c59f6d,- **Real-Time Data**: Use **WebSockets** ([Soc...,{'doc_id': 'ebde81f4-9975-433d-a618-b683e2a427...
4,"[-5.812119e-05, 0.009987792, -0.17804788, -0.0...",bb3d174d-b334-4c82-a4c2-1865c7124bab,- **Push Notifications (Optional)**: If real-t...,{'doc_id': 'ebde81f4-9975-433d-a618-b683e2a427...
5,"[0.044177365, 0.038153738, -0.18291418, -0.038...",d6bfa610-9790-44ae-a900-ac421c32d809,### 2. **Data Flow and Logic**,{'doc_id': 'ebde81f4-9975-433d-a618-b683e2a427...
6,"[0.044177365, 0.038153738, -0.18291418, -0.038...",5be45eb5-029e-412f-ad7b-97b50da7e536,### 2. **Data Flow and Logic**,{'doc_id': 'e099fc60-50b0-417e-b135-8792c18937...
7,"[-0.056409307, 0.062862284, -0.16527662, -0.01...",c7a515d5-7da9-444a-87dc-bf9fdfd7601f,- **Step 1: Group Management**: When users cre...,{'doc_id': 'e099fc60-50b0-417e-b135-8792c18937...
8,"[0.016148074, 0.008072146, -0.18886997, -0.020...",74d6d98e-bf22-41ef-8724-a00804dc8001,"- **Step 2: Location Updates**: Every minute, ...",{'doc_id': 'e099fc60-50b0-417e-b135-8792c18937...
9,"[-0.009986808, 0.034111794, -0.18342674, -0.03...",f870d90f-3f62-445f-a786-8eb300ebdee1,- The backend identifies the user’s group.\n ...,{'doc_id': 'e099fc60-50b0-417e-b135-8792c18937...