In [1]:
import os

os.getcwd()

'/home/asutosh/Documents/projects/ml_projects/nexus-local/src/notebooks'

In [2]:
import sqlite3

DB_PATH = "../../data/sqlite/nexus.db"
def get_all_tables(db_path=DB_PATH):
    with sqlite3.connect(db_path) as conn:
        cursor = conn.cursor()
        cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
        return [row[0] for row in cursor.fetchall()]

def get_table_data(table_name, db_path=DB_PATH):
    import pandas as pd
    with sqlite3.connect(db_path) as conn:
        return pd.read_sql_query(f"SELECT * FROM {table_name}", conn)

In [3]:
get_all_tables()

['chats', 'messages', 'sqlite_sequence', 'watched_paths']

In [4]:
get_table_data('watched_paths')

Empty DataFrame
Columns: [id, path, table_name, status, last_scan, strategy, created_at]
Index: []

In [5]:
get_table_data('messages')

,id,chat_id,role,content,created_at
0,140,bf9e5ecf-657e-4cce-ac47-e3762192f240,user,who are you?,2026-02-08 18:03:15.796955
1,141,bf9e5ecf-657e-4cce-ac47-e3762192f240,assistant,"I am Nexus, a specialized research assistant d...",2026-02-08 18:04:42.092766
2,142,bf9e5ecf-657e-4cce-ac47-e3762192f240,user,when were you built?,2026-02-08 18:05:00.979318
3,143,bf9e5ecf-657e-4cce-ac47-e3762192f240,assistant,"I'm a large language model, I don't have a spe...",2026-02-08 18:05:47.570204
4,144,af74dcac-d450-4b2e-96b1-ede5d0e66618,user,give me the best 3 writing tips from my notes,2026-02-08 22:27:15.303532
5,145,af74dcac-d450-4b2e-96b1-ede5d0e66618,assistant,I couldn't find any writing tips in your notes...,2026-02-08 22:27:25.014989
6,146,af74dcac-d450-4b2e-96b1-ede5d0e66618,user,give me best 3 writing tips from my local storage,2026-02-08 22:28:06.296160
7,147,af74dcac-d450-4b2e-96b1-ede5d0e66618,assistant,It seems like the `local_search_tool` didn't f...,2026-02-08 22:28:14.177746
8,148,e2399c9f-d1e0-49a9-9918-04464b481cc8,user,give me best 3 writing tips from my local stor...,2026-02-08 22:28:30.891566
9,149,e2399c9f-d1e0-49a9-9918-04464b481cc8,assistant,It seems that I couldn't find any writing tips...,2026-02-08 22:28:36.047575

In [6]:
import lancedb
import pandas as pd

LANCEDB_PATH = "../../data/lancedb"

def list_lancedb_tables(db_path: str):
    """List all tables in the specified LanceDB database."""
    db = lancedb.connect(db_path)
    print(f'db: {db}')
    return db.table_names()

def preview_lancedb_table(db_path: str, table_name: str):
    """Preview the specified table from LanceDB."""
    db = lancedb.connect(db_path)
    print(f'db: {db}')
    table = db.open_table(table_name)
    df = table.search().to_pandas()
    return df

In [9]:
tables = list_lancedb_tables(LANCEDB_PATH)
tables

db: LanceDBConnection(uri='/home/asutosh/Documents/projects/ml_projects/nexus-local/src/notebooks/../../data/lancedb')

/tmp/ipykernel_19043/2108785660.py:10: DeprecationWarning: table_names() is deprecated, use list_tables() instead
  return db.table_names()

['folder_file_watcher_test']

In [10]:
df = preview_lancedb_table(LANCEDB_PATH, tables[0])
print(f'df: {len(df)}')
df.head(25)

db: LanceDBConnection(uri='/home/asutosh/Documents/projects/ml_projects/nexus-local/src/notebooks/../../data/lancedb')
df: 305

,vector,id,text,metadata
0,"[-0.0056323456, 0.051364634, -0.2045191, -0.05...",cb1c134d-9205-418e-8462-429adba85b44,[Date and Time of Illustration – 18 January 20...,"{'author': 'asutosh', 'doc_id': 'b1b00adf-c37e..."
1,"[0.014247041, 0.046016082, -0.18624954, -0.031...",bdf58c6d-8d4f-4c2e-8cfe-c2c064b9c974,"Tag Line:\nGST Rate (Base Policy, First Year):...","{'author': 'asutosh', 'doc_id': 'b1b00adf-c37e..."
2,"[0.003739439, 0.06869201, -0.16764252, -0.0364...",6143f070-a6eb-4f92-9fad-2c8711a32011,104N127V04\nHaryana\nODISHA\n0.00%\nProposal N...,"{'author': 'asutosh', 'doc_id': 'b1b00adf-c37e..."
3,"[0.02120235, -0.00621535, -0.20570385, -0.0247...",55a1d7a7-5bee-497f-8d6a-2d23f94b515a,Risk Class: Non-Smoker\nRider Details\nRider N...,"{'author': 'asutosh', 'doc_id': 'b1b00adf-c37e..."
4,"[0.05429778, 0.012234492, -0.18630277, -0.0027...",08f44cb8-cb21-4a7b-8d6d-8b2a9e382e85,No\nSum Assured\nNA\nCoverage Term\nNA\nPaymen...,"{'author': 'asutosh', 'doc_id': 'b1b00adf-c37e..."
5,"[0.044647053, 0.029678723, -0.18951619, -0.000...",a7106296-eab4-4980-858c-013ef00b457b,Premium Summary\nType Base Plan Maternity Cove...,"{'author': 'asutosh', 'doc_id': '318effb3-e3e8..."
6,"[0.00021396625, 0.018620793, -0.18772471, -0.0...",197535e1-d187-48d8-93c8-c8afa6506d42,"0\n0\n0\n900\n900\n900\n0\n0\n0\n0\n0\n0\n3,41...","{'author': 'asutosh', 'doc_id': '318effb3-e3e8..."
7,"[0.0005202517, -0.0023335326, -0.17138703, -0....",a132b57b-2f9d-4c4d-9250-d44c1e869197,"1 28,540 0 0 0 3,00,00,000 0 0 NA NA NA\n2 33,...","{'author': 'asutosh', 'doc_id': '318effb3-e3e8..."
8,"[0.020044433, 0.033354353, -0.17315544, -0.059...",14b7bcca-1d9a-4923-8dec-add28d48db71,"9 33,576 0 0 0 3,00,00,000 0 0 NA NA NA\n10 33...","{'author': 'asutosh', 'doc_id': '318effb3-e3e8..."
9,"[0.017924717, 0.06776391, -0.16719878, -0.0329...",94531b36-bf8e-4ead-b064-72b09ff7d2df,"17 33,576 0 0 0 3,00,00,000 0 0 NA NA NA\n18 3...","{'author': 'asutosh', 'doc_id': '318effb3-e3e8..."
10,"[0.0024389497, -0.0021778122, -0.18531212, -0....",b08ab8a7-99fa-4d84-9ecf-081a309a7e35,Signature / Thumb Impression / Electronic...,"{'author': 'asutosh', 'doc_id': '714337d8-da7a..."
11,"[-0.009661157, 0.03492563, -0.16558854, -0.029...",cf173ffb-a66c-4b7e-b17d-6b512da731e2,"1/18/26 1/18/26\nI, Mr.Asutosh(name), having...","{'author': 'asutosh', 'doc_id': '714337d8-da7a..."
12,"[-0.009606093, 0.007507119, -0.19314994, -0.07...",3dc1b0bf-1050-4b0f-ab8c-7a99d8dbdc56,"Loyalty Additions\nOther Benefits, if\nany Mat...","{'author': 'asutosh', 'doc_id': '714337d8-da7a..."
13,"[0.0036645918, 0.021215918, -0.16228034, -0.04...",95a6e942-5443-4d8a-9b4c-78b67c395bf4,"28 33,576 0 0 0 3,00,00,000 0 0 NA NA NA\n29 3...","{'author': 'asutosh', 'doc_id': '714337d8-da7a..."
14,"[0.005045547, 0.080126785, -0.18887822, -0.020...",c6e2f315-5db4-4bbb-9d31-b49c66716867,"32 33,576 0 0 0 3,00,00,000 0 0 NA NA NA\nNote...","{'author': 'asutosh', 'doc_id': '714337d8-da7a..."
15,"[-0.025971143, 0.0780916, -0.15269879, -0.0705...",aae4e1af-2f6f-451c-996a-63ad0b5708b9,You are an expert Python developer specialized...,"{'author': 'asutosh', 'doc_id': 'da65ba03-2b4c..."
16,"[0.037109442, -0.014749927, -0.17752303, -0.06...",ce4efa0e-353c-4b50-af33-4d33924f6e40,Monitor: A background service watches for file...,"{'author': 'asutosh', 'doc_id': 'da65ba03-2b4c..."
17,"[0.0014451595, -0.01157726, -0.17531668, -0.05...",a5cbadd9-f8a1-40c5-bd48-4876f0d318ac,Implementation Plan\nPhase 1: Database Schema ...,"{'author': 'asutosh', 'doc_id': 'da65ba03-2b4c..."
18,"[0.0015199683, -0.022660406, -0.19008884, -0.0...",84860215-d516-47a4-956a-51f23fc7383f,status (TEXT): 'active' or 'paused'.\n\nlast_s...,"{'author': 'asutosh', 'doc_id': 'da65ba03-2b4c..."
19,"[0.029098911, 0.0065061124, -0.18282017, -0.02...",56eefe52-3665-442b-a59a-98123a09a76d,Logic: When a folder is selected:\n\nCheck if ...,"{'author': 'asutosh', 'doc_id': 'da65ba03-2b4c..."
20,"[0.021330392, 0.016499206, -0.16748706, -0.043...",4a4dabab-28ac-4141-94a8-9007e4a7e061,Step A (Purge): Search the generic documents &...,"{'author': 'asutosh', 'doc_id': 'da65ba03-2b4c..."
21,"[0.010102967, 0.034939893, -0.17364876, -0.046...",a772a087-ce8c-480a-89a7-c50a8c90ddba,Step A (Purge): Search the generic documents &...,"{'author': 'asutosh', 'doc_id': '376e51a2-6814..."
22,"[-0.004024411, -0.012562131, -0.19387066, -0.0...",316c1de9-1377-44a7-8817-62eb2b9ba8b0,Step D (Record): Save metadata to watched_path...,"{'author': 'asutosh', 'doc_id': '376e51a2-6814..."
23,"[0.05826486, 0.022995686, -0.13880844, -0.0590...",fcc49981-9784-4a45-b715-a02cac461354,Debounce: Wait 2-3 seconds after an event to e...,"{'author': 'asutosh', 'doc_id': '376e51a2-6814..."
24,"[0.021554157, 0.02608164, -0.15565872, -0.0714...",535e4116-8a79-48f1-9b2a-504339e7644a,Phase 5: The Organizer Logic (LLM Agent)\nActi...,"{'author': 'asutosh', 'doc_id': '376e51a2-6814..."

In [12]:
for row in df.iterrows():
    print(f">> {row[1]['metadata']}")

>> {'author': 'asutosh', 'doc_id': 'b1b00adf-c37e-4c1a-adad-ca0566482988', 'extra_metadata': '{"producer": "iText\\u00ae 5.5.11 \\u00a92000-2017 iText Group NV (AGPL-version)", "creator": "PyPDF", "creationdate": "2026-01-18T15:44:22+05:30", "moddate": "2026-01-18T15:44:22+05:30", "total_pages": 3, "page_label": "1"}', 'page': 0, 'source': '/home/asutosh/Downloads/file_watcher_test/190217091-BI.pdf'}
>> {'author': 'asutosh', 'doc_id': 'b1b00adf-c37e-4c1a-adad-ca0566482988', 'extra_metadata': '{"producer": "iText\\u00ae 5.5.11 \\u00a92000-2017 iText Group NV (AGPL-version)", "creator": "PyPDF", "creationdate": "2026-01-18T15:44:22+05:30", "moddate": "2026-01-18T15:44:22+05:30", "total_pages": 3, "page_label": "1"}', 'page': 0, 'source': '/home/asutosh/Downloads/file_watcher_test/190217091-BI.pdf'}
>> {'author': 'asutosh', 'doc_id': 'b1b00adf-c37e-4c1a-adad-ca0566482988', 'extra_metadata': '{"producer": "iText\\u00ae 5.5.11 \\u00a92000-2017 iText Group NV (AGPL-version)", "creator": "PyPDF", "creationdate": "2026-01-18T15:44:22+05:30", "moddate": "2026-01-18T15:44:22+05:30", "total_pages": 3, "page_label": "1"}', 'page': 0, 'source': '/home/asutosh/Downloads/file_watcher_test/190217091-BI.pdf'}
>> {'author': 'asutosh', 'doc_id': 'b1b00adf-c37e-4c1a-adad-ca0566482988', 'extra_metadata': '{"producer": "iText\\u00ae 5.5.11 \\u00a92000-2017 iText Group NV (AGPL-version)", "creator": "PyPDF", "creationdate": "2026-01-18T15:44:22+05:30", "moddate": "2026-01-18T15:44:22+05:30", "total_pages": 3, "page_label": "1"}', 'page': 0, 'source': '/home/asutosh/Downloads/file_watcher_test/190217091-BI.pdf'}
>> {'author': 'asutosh', 'doc_id': 'b1b00adf-c37e-4c1a-adad-ca0566482988', 'extra_metadata': '{"producer": "iText\\u00ae 5.5.11 \\u00a92000-2017 iText Group NV (AGPL-version)", "creator": "PyPDF", "creationdate": "2026-01-18T15:44:22+05:30", "moddate": "2026-01-18T15:44:22+05:30", "total_pages": 3, "page_label": "1"}', 'page': 0, 'source': '/home/asutosh/Downloads/file_watcher_test/190217091-BI.pdf'}
>> {'author': 'asutosh', 'doc_id': '318effb3-e3e8-487c-8c64-88d5ee1f2d56', 'extra_metadata': '{"producer": "iText\\u00ae 5.5.11 \\u00a92000-2017 iText Group NV (AGPL-version)", "creator": "PyPDF", "creationdate": "2026-01-18T15:44:22+05:30", "moddate": "2026-01-18T15:44:22+05:30", "total_pages": 3, "page_label": "2"}', 'page': 1, 'source': '/home/asutosh/Downloads/file_watcher_test/190217091-BI.pdf'}
>> {'author': 'asutosh', 'doc_id': '318effb3-e3e8-487c-8c64-88d5ee1f2d56', 'extra_metadata': '{"producer": "iText\\u00ae 5.5.11 \\u00a92000-2017 iText Group NV (AGPL-version)", "creator": "PyPDF", "creationdate": "2026-01-18T15:44:22+05:30", "moddate": "2026-01-18T15:44:22+05:30", "total_pages": 3, "page_label": "2"}', 'page': 1, 'source': '/home/asutosh/Downloads/file_watcher_test/190217091-BI.pdf'}
>> {'author': 'asutosh', 'doc_id': '318effb3-e3e8-487c-8c64-88d5ee1f2d56', 'extra_metadata': '{"producer": "iText\\u00ae 5.5.11 \\u00a92000-2017 iText Group NV (AGPL-version)", "creator": "PyPDF", "creationdate": "2026-01-18T15:44:22+05:30", "moddate": "2026-01-18T15:44:22+05:30", "total_pages": 3, "page_label": "2"}', 'page': 1, 'source': '/home/asutosh/Downloads/file_watcher_test/190217091-BI.pdf'}
>> {'author': 'asutosh', 'doc_id': '318effb3-e3e8-487c-8c64-88d5ee1f2d56', 'extra_metadata': '{"producer": "iText\\u00ae 5.5.11 \\u00a92000-2017 iText Group NV (AGPL-version)", "creator": "PyPDF", "creationdate": "2026-01-18T15:44:22+05:30", "moddate": "2026-01-18T15:44:22+05:30", "total_pages": 3, "page_label": "2"}', 'page': 1, 'source': '/home/asutosh/Downloads/file_watcher_test/190217091-BI.pdf'}
>> {'author': 'asutosh', 'doc_id': '318effb3-e3e8-487c-8c64-88d5ee1f2d56', 'extra_metadata': '{"producer": "iText\\u00ae 5.5.11 \\u00a92000-2017 iText Group NV (AGPL-version)", "creator": "PyPDF", "creationdate": "2026-01-18T15:44:22+05:30", "moddate": "2026-01-18T15:44:22+05:30", "total_pages": 3, "page_label": "2"}', 'page': 1, 'source': '/home/asutosh/Downloads/file_watcher_test/190217091-BI.pdf'}
>> {'author': 'asutosh', 'doc_id': '714337d8-da7a-4a70-bcff-1fecd4836424', 'extra_metadata': '{"producer": "iText\\u00ae 5.5.11 \\u00a92000-2017 iText Group NV (AGPL-version)", "creator": "PyPDF", "creationdate": "2026-01-18T15:44:22+05:30", "moddate": "2026-01-18T15:44:22+05:30", "total_pages": 3, "page_label": "3"}', 'page': 2, 'source': '/home/asutosh/Downloads/file_watcher_test/190217091-BI.pdf'}
>> {'author': 'asutosh', 'doc_id': '714337d8-da7a-4a70-bcff-1fecd4836424', 'extra_metadata': '{"producer": "iText\\u00ae 5.5.11 \\u00a92000-2017 iText Group NV (AGPL-version)", "creator": "PyPDF", "creationdate": "2026-01-18T15:44:22+05:30", "moddate": "2026-01-18T15:44:22+05:30", "total_pages": 3, "page_label": "3"}', 'page': 2, 'source': '/home/asutosh/Downloads/file_watcher_test/190217091-BI.pdf'}
>> {'author': 'asutosh', 'doc_id': '714337d8-da7a-4a70-bcff-1fecd4836424', 'extra_metadata': '{"producer": "iText\\u00ae 5.5.11 \\u00a92000-2017 iText Group NV (AGPL-version)", "creator": "PyPDF", "creationdate": "2026-01-18T15:44:22+05:30", "moddate": "2026-01-18T15:44:22+05:30", "total_pages": 3, "page_label": "3"}', 'page': 2, 'source': '/home/asutosh/Downloads/file_watcher_test/190217091-BI.pdf'}
>> {'author': 'asutosh', 'doc_id': '714337d8-da7a-4a70-bcff-1fecd4836424', 'extra_metadata': '{"producer": "iText\\u00ae 5.5.11 \\u00a92000-2017 iText Group NV (AGPL-version)", "creator": "PyPDF", "creationdate": "2026-01-18T15:44:22+05:30", "moddate": "2026-01-18T15:44:22+05:30", "total_pages": 3, "page_label": "3"}', 'page': 2, 'source': '/home/asutosh/Downloads/file_watcher_test/190217091-BI.pdf'}
>> {'author': 'asutosh', 'doc_id': '714337d8-da7a-4a70-bcff-1fecd4836424', 'extra_metadata': '{"producer": "iText\\u00ae 5.5.11 \\u00a92000-2017 iText Group NV (AGPL-version)", "creator": "PyPDF", "creationdate": "2026-01-18T15:44:22+05:30", "moddate": "2026-01-18T15:44:22+05:30", "total_pages": 3, "page_label": "3"}', 'page': 2, 'source': '/home/asutosh/Downloads/file_watcher_test/190217091-BI.pdf'}
>> {'author': 'asutosh', 'doc_id': 'da65ba03-2b4c-4248-a774-4b28cae8284b', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/file-watcher-instruction.txt'}
>> {'author': 'asutosh', 'doc_id': 'da65ba03-2b4c-4248-a774-4b28cae8284b', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/file-watcher-instruction.txt'}
>> {'author': 'asutosh', 'doc_id': 'da65ba03-2b4c-4248-a774-4b28cae8284b', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/file-watcher-instruction.txt'}
>> {'author': 'asutosh', 'doc_id': 'da65ba03-2b4c-4248-a774-4b28cae8284b', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/file-watcher-instruction.txt'}
>> {'author': 'asutosh', 'doc_id': 'da65ba03-2b4c-4248-a774-4b28cae8284b', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/file-watcher-instruction.txt'}
>> {'author': 'asutosh', 'doc_id': 'da65ba03-2b4c-4248-a774-4b28cae8284b', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/file-watcher-instruction.txt'}
>> {'author': 'asutosh', 'doc_id': '376e51a2-6814-445c-a713-11e988f315be', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/file-watcher-instruction.txt'}
>> {'author': 'asutosh', 'doc_id': '376e51a2-6814-445c-a713-11e988f315be', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/file-watcher-instruction.txt'}
>> {'author': 'asutosh', 'doc_id': '376e51a2-6814-445c-a713-11e988f315be', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/file-watcher-instruction.txt'}
>> {'author': 'asutosh', 'doc_id': '376e51a2-6814-445c-a713-11e988f315be', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/file-watcher-instruction.txt'}
>> {'author': 'asutosh', 'doc_id': '376e51a2-6814-445c-a713-11e988f315be', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/file-watcher-instruction.txt'}
>> {'author': 'asutosh', 'doc_id': '376e51a2-6814-445c-a713-11e988f315be', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/file-watcher-instruction.txt'}
>> {'author': 'asutosh', 'doc_id': 'bd234f5b-554c-4d12-bf4a-79e12f401239', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/file-watcher-instruction.txt'}
>> {'author': 'asutosh', 'doc_id': 'bd234f5b-554c-4d12-bf4a-79e12f401239', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/file-watcher-instruction.txt'}
>> {'author': 'asutosh', 'doc_id': 'bd234f5b-554c-4d12-bf4a-79e12f401239', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/file-watcher-instruction.txt'}
>> {'author': 'asutosh', 'doc_id': '407e04d8-379a-4912-9821-208804074ec3', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/pip-packaging-instruction.txt'}
>> {'author': 'asutosh', 'doc_id': '407e04d8-379a-4912-9821-208804074ec3', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/pip-packaging-instruction.txt'}
>> {'author': 'asutosh', 'doc_id': '407e04d8-379a-4912-9821-208804074ec3', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/pip-packaging-instruction.txt'}
>> {'author': 'asutosh', 'doc_id': '407e04d8-379a-4912-9821-208804074ec3', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/pip-packaging-instruction.txt'}
>> {'author': 'asutosh', 'doc_id': '407e04d8-379a-4912-9821-208804074ec3', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/pip-packaging-instruction.txt'}
>> {'author': 'asutosh', 'doc_id': '407e04d8-379a-4912-9821-208804074ec3', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/pip-packaging-instruction.txt'}
>> {'author': 'asutosh', 'doc_id': '407e04d8-379a-4912-9821-208804074ec3', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/pip-packaging-instruction.txt'}
>> {'author': 'asutosh', 'doc_id': 'c05572ed-1682-4dfd-af7e-90699cc2d8de', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/pip-packaging-instruction.txt'}
>> {'author': 'asutosh', 'doc_id': 'c05572ed-1682-4dfd-af7e-90699cc2d8de', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/pip-packaging-instruction.txt'}
>> {'author': 'asutosh', 'doc_id': 'c05572ed-1682-4dfd-af7e-90699cc2d8de', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/pip-packaging-instruction.txt'}
>> {'author': 'asutosh', 'doc_id': 'c05572ed-1682-4dfd-af7e-90699cc2d8de', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/pip-packaging-instruction.txt'}
>> {'author': 'asutosh', 'doc_id': 'c05572ed-1682-4dfd-af7e-90699cc2d8de', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/pip-packaging-instruction.txt'}
>> {'author': 'asutosh', 'doc_id': 'c05572ed-1682-4dfd-af7e-90699cc2d8de', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/pip-packaging-instruction.txt'}
>> {'author': 'asutosh', 'doc_id': 'c05572ed-1682-4dfd-af7e-90699cc2d8de', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/pip-packaging-instruction.txt'}
>> {'author': 'asutosh', 'doc_id': 'dd32a42d-3f8d-4043-b8d2-2a8c0438054d', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/pip-packaging-instruction.txt'}
>> {'author': 'asutosh', 'doc_id': 'dd32a42d-3f8d-4043-b8d2-2a8c0438054d', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/pip-packaging-instruction.txt'}
>> {'author': 'asutosh', 'doc_id': 'dd32a42d-3f8d-4043-b8d2-2a8c0438054d', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/pip-packaging-instruction.txt'}
>> {'author': 'asutosh', 'doc_id': 'dd32a42d-3f8d-4043-b8d2-2a8c0438054d', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/pip-packaging-instruction.txt'}
>> {'author': 'asutosh', 'doc_id': 'dd32a42d-3f8d-4043-b8d2-2a8c0438054d', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/pip-packaging-instruction.txt'}
>> {'author': 'asutosh', 'doc_id': 'dd32a42d-3f8d-4043-b8d2-2a8c0438054d', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/pip-packaging-instruction.txt'}
>> {'author': 'asutosh', 'doc_id': 'dd32a42d-3f8d-4043-b8d2-2a8c0438054d', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/pip-packaging-instruction.txt'}
>> {'author': 'asutosh', 'doc_id': '3f7dd816-fe44-45b0-a6bd-9d85c4aea668', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/nexus-local-logs-debug.txt'}
>> {'author': 'asutosh', 'doc_id': 'ceb28405-252a-42de-ad3c-2a10074e8eb8', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/nexus-local-logs-debug.txt'}
>> {'author': 'asutosh', 'doc_id': 'ceb28405-252a-42de-ad3c-2a10074e8eb8', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/nexus-local-logs-debug.txt'}
>> {'author': 'asutosh', 'doc_id': 'ceb28405-252a-42de-ad3c-2a10074e8eb8', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/nexus-local-logs-debug.txt'}
>> {'author': 'asutosh', 'doc_id': 'ceb28405-252a-42de-ad3c-2a10074e8eb8', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/nexus-local-logs-debug.txt'}
>> {'author': 'asutosh', 'doc_id': 'ceb28405-252a-42de-ad3c-2a10074e8eb8', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/nexus-local-logs-debug.txt'}
>> {'author': 'asutosh', 'doc_id': 'ceb28405-252a-42de-ad3c-2a10074e8eb8', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/nexus-local-logs-debug.txt'}
>> {'author': 'asutosh', 'doc_id': 'c46e2314-8d44-4158-a9a1-f23aad310191', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/nexus-local-logs-debug.txt'}
>> {'author': 'asutosh', 'doc_id': 'c46e2314-8d44-4158-a9a1-f23aad310191', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/nexus-local-logs-debug.txt'}
>> {'author': 'asutosh', 'doc_id': 'c46e2314-8d44-4158-a9a1-f23aad310191', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/nexus-local-logs-debug.txt'}
>> {'author': 'asutosh', 'doc_id': 'd93edc99-f5aa-4079-bff7-42226470b876', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/nexus-local-logs-debug.txt'}
>> {'author': 'asutosh', 'doc_id': 'd93edc99-f5aa-4079-bff7-42226470b876', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/nexus-local-logs-debug.txt'}
>> {'author': 'asutosh', 'doc_id': 'd93edc99-f5aa-4079-bff7-42226470b876', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/nexus-local-logs-debug.txt'}
>> {'author': 'asutosh', 'doc_id': 'd93edc99-f5aa-4079-bff7-42226470b876', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/nexus-local-logs-debug.txt'}
>> {'author': 'asutosh', 'doc_id': 'd93edc99-f5aa-4079-bff7-42226470b876', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/nexus-local-logs-debug.txt'}
>> {'author': 'asutosh', 'doc_id': 'd93edc99-f5aa-4079-bff7-42226470b876', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/nexus-local-logs-debug.txt'}
>> {'author': 'asutosh', 'doc_id': 'd93edc99-f5aa-4079-bff7-42226470b876', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/nexus-local-logs-debug.txt'}
>> {'author': 'asutosh', 'doc_id': 'd93edc99-f5aa-4079-bff7-42226470b876', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/nexus-local-logs-debug.txt'}
>> {'author': 'asutosh', 'doc_id': '24bf063b-323a-42cd-a161-48053f6f3c57', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/nexus-local-logs-debug.txt'}
>> {'author': 'asutosh', 'doc_id': '24bf063b-323a-42cd-a161-48053f6f3c57', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/nexus-local-logs-debug.txt'}
>> {'author': 'asutosh', 'doc_id': 'b279cc6d-ed91-4f75-9168-be577cd39740', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/nexus-local-logs-debug.txt'}
>> {'author': 'asutosh', 'doc_id': 'b279cc6d-ed91-4f75-9168-be577cd39740', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/nexus-local-logs-debug.txt'}
>> {'author': 'asutosh', 'doc_id': 'b279cc6d-ed91-4f75-9168-be577cd39740', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/nexus-local-logs-debug.txt'}
>> {'author': 'asutosh', 'doc_id': 'b279cc6d-ed91-4f75-9168-be577cd39740', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/nexus-local-logs-debug.txt'}
>> {'author': 'asutosh', 'doc_id': 'b279cc6d-ed91-4f75-9168-be577cd39740', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/nexus-local-logs-debug.txt'}
>> {'author': 'asutosh', 'doc_id': 'b279cc6d-ed91-4f75-9168-be577cd39740', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/nexus-local-logs-debug.txt'}
>> {'author': 'asutosh', 'doc_id': '75a87705-e8bb-43cf-a24e-4937bc780f91', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/nexus-local-logs-debug.txt'}
>> {'author': 'asutosh', 'doc_id': '75a87705-e8bb-43cf-a24e-4937bc780f91', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/nexus-local-logs-debug.txt'}
>> {'author': 'asutosh', 'doc_id': '75a87705-e8bb-43cf-a24e-4937bc780f91', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/nexus-local-logs-debug.txt'}
>> {'author': 'asutosh', 'doc_id': '75a87705-e8bb-43cf-a24e-4937bc780f91', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/nexus-local-logs-debug.txt'}
>> {'author': 'asutosh', 'doc_id': '75a87705-e8bb-43cf-a24e-4937bc780f91', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/nexus-local-logs-debug.txt'}
>> {'author': 'asutosh', 'doc_id': '75a87705-e8bb-43cf-a24e-4937bc780f91', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/nexus-local-logs-debug.txt'}
>> {'author': 'asutosh', 'doc_id': '2e687536-b387-4bba-8051-f242873c9e94', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/nexus-local-logs-debug.txt'}
>> {'author': 'asutosh', 'doc_id': '2e687536-b387-4bba-8051-f242873c9e94', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/nexus-local-logs-debug.txt'}
>> {'author': 'asutosh', 'doc_id': '2e687536-b387-4bba-8051-f242873c9e94', 'extra_metadata': '{}', 'page': None, 'source': '/home/asutosh/Downloads/file_watcher_test/nexus-local-logs-debug.txt'}

In [ ]:
!ls '../../../../../'

 dashcam_complain		       'Procedural Generation in Games'
'google sys design 2 interview sheet'   projects
 ingested_docs			        scripts
 installations			        temp
 models				        temp1
 moltbook-agent			        temp_docs
 nayash.github.io		        Twine
 nayash.github.io-copy		        VIDEO_25072025194247_1753452767879.mp4
 notes

In [ ]:
for root, _, files in os.walk('../../../../../ingested_docs'):
    print(f'root={root}, _={_}, files={files}')

root=../../../../../ingested_docs, _=['Private & Shared'], files=['NestedLearning.pdf']
root=../../../../../ingested_docs/Private & Shared, _=['Project Ideas'], files=['Project Ideas 70e616392f9446499e6f7da93016ddcf_all.csv', 'Project Ideas 70e616392f9446499e6f7da93016ddcf.csv']
root=../../../../../ingested_docs/Private & Shared/Project Ideas, _=['Recommendation system', '@Side-Hustle Ideas', 'Writing ideas', 'Nexus Local', 'TripMate'], files=['Notion templates to sell 283f28196ab68006a5abea65343349c1.md', 'Nexus Local 2edf28196ab68069b5b3c793ee2d68cb.md', 'Chrome extension to save snippets 282f28196ab680f19319c5036dc02319.md', 'Android expense tracker 258f28196ab680c4946efcbfb3be4ded.md', 'Recommendation system 106f28196ab680e38b96dcc192f58323.md', 'Writing ideas eb82935e544e4f55a7721b855efdd7af.md', 'Text Based Adventure - Abaddon Hotel cae65a64c0e04f8a9c64898ed4bda2a2.md', 'Android Chat Agent 258f28196ab680168ea1ffcbc1bdd26c.md', 'TripMate efd9cb3c97f04ae8ab8e67e78cd0a814.md', 'Android App for 2D, 3D geometry drawing & calculat 288f28196ab68058a0ebf86c20345afa.md', 'Android auto completion keyboard 288f28196ab680849b69c5f8c71c1576.md', 'P2P on Android ef0d33164c9f4a47a03cebbfff55196c.md', '@Side-Hustle Ideas 288f28196ab68037a8c9f93235e39762.md', '[Game] simple, adictive, level-based game built us 2c6f28196ab6809c8b06f6e847143ef6.md', '[cancel] Extension to do google search on text sel 289f28196ab6804c8f4ddb91d6ff7d3f.md', '[App] smart launcher with full home support using  2c6f28196ab680369f7dd21b15201849.md', 'E-Book publishing 223f28196ab68023b6d9d7bb458f8ec2.md', '[Game] multiplayer game like Undercover 2c6f28196ab680cc8b15e2699720448f.md', 'Sell on Gumroad 262f28196ab68070860cc077cbe468fa.md', '[Game] Jigsaw puzzle 2d7f28196ab680608e2bc6d5bd54da59.md', '[App] show word meaning as popup pn context menu c 292f28196ab680bea984e0982c4e9ad1.md', 'Try anti gravity ide 2edf28196ab680ae94eeebc82a44b44b.md', '[Game] Neon Rebus (Emoji translation) 2d5f28196ab680b485ffe1a24a9ad49a.md', '[Game] MemShuffle тАФ Card shuffle memory 2d5f28196ab6806bbaf4e01779f2e719.md']
root=../../../../../ingested_docs/Private & Shared/Project Ideas/Recommendation system, _=[], files=['Screenshot_from_2025-08-16_19-09-20.png']
root=../../../../../ingested_docs/Private & Shared/Project Ideas/@Side-Hustle Ideas, _=[], files=['NotebookLM Edu Videos 2edf28196ab680fcbd44ef788863769e.md']
root=../../../../../ingested_docs/Private & Shared/Project Ideas/Writing ideas, _=[], files=['Writing tips 236f28196ab680f1be3df0c5a13372d1.md', 'E-Book Ideas 27af28196ab68093bbcbe32bd8de95bf.md', 'DINOv3 250f28196ab68138a4bede4b4afa2466.md']
root=../../../../../ingested_docs/Private & Shared/Project Ideas/Nexus Local, _=[], files=['Product Requirement Document (PRD) Nexus-Local 2f1f28196ab680488781d6e64a33ddbe.md']
root=../../../../../ingested_docs/Private & Shared/Project Ideas/TripMate, _=[], files=['Commands a502fc8b63044edfae5143caee97322a.md', 'ChatGPT response 132f28196ab680a180a2f532d8613628.md']